### ISSUE TITLE
EOS Data

### ISSUE THREAD

**Issue by johnlarkin1** [hardmaru/write-rnn-tensorflow#22]
Hello, 

Just wanted to clarify something. The data is arranged in x, y, eos - but you have the following line of code:
`z_eos = z[:, 0:1]`

This would say grab the first column. However, shouldn't it be something like:
`z_eos = z[:,2]`

Do you somehow rearrange the data around?

**Comment by hardmaru** [comment]
z is the output tensor, now the data format.

we chose to split z into [z_eos, z_pi, z_mu1, z_mu2, z_sigma1, z_sigma2, z_corr], so z_eos is the first column

z_eos = z[:, 0:1]
z_pi, z_mu1, z_mu2, z_sigma1, z_sigma2, z_corr = tf.split(axis=1, num_or_size_splits=6, value=z[:, 1:])
